// Generated by CoffeeScript 1.12.3
(function() {
  var app_addition, app_soustraction;

  new Vue({
    el: '#title_app',
    data: {
      message: 'Hi, this website has been built from the ground up to help yungers learn their mathematics.',
      message2: 'Scroll down to start!'
    }
  });

  app_addition = new Vue({
    el: '#container1',
    data: {
      message: 'hello there',
      number_1: '?',
      number_2: '?',
      user_answer: void 0
    },
    methods: {
      calculate: function() {
        if (this.number_1 + this.number_2 === this.user_answer) {
          alert('good');
          return this.restart();
        } else {
          $('#container1 input').removeClass('animated shake');
          return $('#container1 input').addClass('animated shake');
        }
      },
      restart: function() {
        this.number_1 = Math.floor(Math.random() * 10);
        return this.number_2 = Math.floor(Math.random() * 10);
      }
    }
  });

  app_soustraction = new Vue({
    el: '#container2',
    data: {
      message: 'hello there',
      number_1: '?',
      number_2: '?',
      user_answer: void 0
    },
    methods: {
      calculate: function() {
        if (this.number_1 - this.number_2 === this.user_answer) {
          alert('good');
          return this.restart();
        } else {
          $('#container2 input').removeClass('animated shake');
          return $('#container2 input').addClass('animated shake');
        }
      },
      restart: function() {
        this.number_1 = Math.floor(Math.random() * 10);
        return this.number_2 = Math.floor(Math.random() * 10);
      }
    }
  });

  $(document).ready(function() {
    return $('.animate').each(function(i) {
      return setTimeout(function() {
        $('.animate').eq(i).addClass('show');
        $('.animate').eq(i).addClass('animated');
        return $('.animate').eq(i).addClass('fadeIn');
      }, 200 * i);
    });
  });

}).call(this);
